// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/2000ostd/enssi-tel-bot/internal/adapter/imagegen"
	"github.com/2000ostd/enssi-tel-bot/internal/adapter/persistence/postgres"
	"github.com/2000ostd/enssi-tel-bot/internal/adapter/telegram"
	"github.com/2000ostd/enssi-tel-bot/internal/adapter/telegram/handlers/callback"
	"github.com/2000ostd/enssi-tel-bot/internal/adapter/telegram/handlers/command"
	"github.com/2000ostd/enssi-tel-bot/internal/adapter/telegram/handlers/message"
	achievement3 "github.com/2000ostd/enssi-tel-bot/internal/domain/achievement"
	course3 "github.com/2000ostd/enssi-tel-bot/internal/domain/course"
	"github.com/2000ostd/enssi-tel-bot/internal/domain/notification"
	quiz2 "github.com/2000ostd/enssi-tel-bot/internal/domain/quiz"
	user3 "github.com/2000ostd/enssi-tel-bot/internal/domain/user"
	word2 "github.com/2000ostd/enssi-tel-bot/internal/domain/word"
	achievement2 "github.com/2000ostd/enssi-tel-bot/internal/usecase/commands/achievement"
	course2 "github.com/2000ostd/enssi-tel-bot/internal/usecase/commands/course"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/commands/quiz"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/commands/user"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/commands/word"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/jobs"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/queries/achievement"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/queries/course"
	user2 "github.com/2000ostd/enssi-tel-bot/internal/usecase/queries/user"
	"github.com/google/wire"
	"gopkg.in/telebot.v4"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeBotApp creates the dependency graph for the bot application handlers.
func InitializeBotApp(db *gorm.DB) (*BotApp, error) {
	userRepository := postgres.NewUserRepository(db)
	registerUserHandler := user.NewRegisterUserHandler(userRepository)
	achievementRepository := postgres.NewAchievementRepository(db)
	getProfileHandler := user2.NewGetProfileHandler(userRepository, achievementRepository)
	quizRepository := postgres.NewQuizRepository(db)
	handler := command.NewHandler(registerUserHandler, getProfileHandler, userRepository, quizRepository)
	courseRepository := postgres.NewCourseRepository(db)
	listCoursesHandler := course.NewListCoursesHandler(courseRepository)
	getOverviewHandler := course.NewGetOverviewHandler(courseRepository)
	getAllHandler := achievement.NewGetAllHandler(achievementRepository)
	string2 := _wireStringValue
	generator, err := imagegen.NewGenerator(string2)
	if err != nil {
		return nil, err
	}
	wordRepository := postgres.NewWordRepository(db)
	createCourseQuizHandler := quiz.NewCreateCourseQuizHandler(quizRepository, wordRepository)
	advanceWordHandler := course2.NewAdvanceWordHandler(courseRepository, wordRepository, createCourseQuizHandler)
	startSessionHandler := course2.NewStartSessionHandler(courseRepository, wordRepository, createCourseQuizHandler)
	cacheMediaHandler := word.NewCacheMediaHandler(wordRepository)
	messageHandler := message.NewHandler(listCoursesHandler, getOverviewHandler, getProfileHandler, getAllHandler, achievementRepository, generator, advanceWordHandler, startSessionHandler, userRepository, courseRepository, quizRepository, cacheMediaHandler)
	submitAnswerHandler := quiz.NewSubmitAnswerHandler(quizRepository, wordRepository)
	awardProgressHandler := achievement2.NewAwardProgressHandler(achievementRepository)
	handleQuizCompletionHandler := course2.NewHandleQuizCompletionHandler(courseRepository, wordRepository, createCourseQuizHandler, awardProgressHandler)
	callbackHandler := callback.NewHandler(submitAnswerHandler, handleQuizCompletionHandler, quizRepository, achievementRepository, generator, userRepository, getOverviewHandler)
	botApp := &BotApp{
		CommandHandler:  handler,
		MessageHandler:  messageHandler,
		CallbackHandler: callbackHandler,
	}
	return botApp, nil
}

var (
	_wireStringValue = "assets/imgs/achievements_gen"
)

// InitializeWorkerApp creates the dependency graph for the worker application.
func InitializeWorkerApp(db *gorm.DB, bot *telebot.Bot) (*WorkerApp, error) {
	userRepository := postgres.NewUserRepository(db)
	wordRepository := postgres.NewWordRepository(db)
	quizRepository := postgres.NewQuizRepository(db)
	createReviewQuizHandler := quiz.NewCreateReviewQuizHandler(quizRepository)
	notifier := telegram.NewNotifier(bot, userRepository)
	triggerDailyReviewsJob := jobs.NewTriggerDailyReviewsJob(userRepository, wordRepository, createReviewQuizHandler, notifier)
	workerApp := &WorkerApp{
		TriggerDailyReviewsJob: triggerDailyReviewsJob,
	}
	return workerApp, nil
}

// InitializeRegisterUserHandler is a helper to get just the user registration use case.
// This is a temporary solution to simplify wiring the middleware in main.go.
func InitializeRegisterUserHandler(db *gorm.DB) user.RegisterUserHandler {
	userRepository := postgres.NewUserRepository(db)
	registerUserHandler := user.NewRegisterUserHandler(userRepository)
	return registerUserHandler
}

// wire.go:

// BotApp contains the dependencies for the Telegram bot entry point.
type BotApp struct {
	CommandHandler  *command.Handler
	MessageHandler  *message.Handler
	CallbackHandler *callback.Handler
}

// WorkerApp contains the dependencies for the background worker entry point.
type WorkerApp struct {
	TriggerDailyReviewsJob *jobs.TriggerDailyReviewsJob
}

var userSet = wire.NewSet(postgres.NewUserRepository, wire.Bind(new(user3.Repository), new(*postgres.UserRepository)), user.NewRegisterUserHandler, user2.NewGetProfileHandler)

var courseSet = wire.NewSet(postgres.NewCourseRepository, wire.Bind(new(course3.Repository), new(*postgres.CourseRepository)), course.NewListCoursesHandler, course.NewGetOverviewHandler, course2.NewStartSessionHandler, course2.NewAdvanceWordHandler, course2.NewHandleQuizCompletionHandler)

var wordSet = wire.NewSet(postgres.NewWordRepository, wire.Bind(new(word2.Repository), new(*postgres.WordRepository)))

var quizSet = wire.NewSet(postgres.NewQuizRepository, wire.Bind(new(quiz2.Repository), new(*postgres.QuizRepository)), quiz.NewCreateCourseQuizHandler, quiz.NewCreateReviewQuizHandler, quiz.NewSubmitAnswerHandler)

var achievementSet = wire.NewSet(postgres.NewAchievementRepository, wire.Bind(new(achievement3.Repository), new(*postgres.AchievementRepository)), achievement2.NewAwardProgressHandler, achievement.NewGetAllHandler)

var imagegenSet = wire.NewSet(wire.Value("assets/imgs/achievements_gen"), imagegen.NewGenerator, wire.Bind(new(achievement3.ImageGenerator), new(*imagegen.Generator)))

var notifierSet = wire.NewSet(telegram.NewNotifier, wire.Bind(new(notification.Notifier), new(*telegram.Notifier)))

var wordCacheSet = wire.NewSet(word.NewCacheMediaHandler)
