// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/2000ostd/enssi-tel-bot/internal/adapter/imagegen"
	"github.com/2000ostd/enssi-tel-bot/internal/adapter/persistence/postgres"
	"github.com/2000ostd/enssi-tel-bot/internal/adapter/telegram"
	"github.com/2000ostd/enssi-tel-bot/internal/adapter/telegram/handlers/callback"
	"github.com/2000ostd/enssi-tel-bot/internal/adapter/telegram/handlers/command"
	"github.com/2000ostd/enssi-tel-bot/internal/adapter/telegram/handlers/message"
	achievement3 "github.com/2000ostd/enssi-tel-bot/internal/domain/achievement"
	course3 "github.com/2000ostd/enssi-tel-bot/internal/domain/course"
	"github.com/2000ostd/enssi-tel-bot/internal/domain/notification"
	quiz2 "github.com/2000ostd/enssi-tel-bot/internal/domain/quiz"
	user3 "github.com/2000ostd/enssi-tel-bot/internal/domain/user"
	word2 "github.com/2000ostd/enssi-tel-bot/internal/domain/word"
	"github.com/2000ostd/enssi-tel-bot/internal/platform/config"
	"github.com/2000ostd/enssi-tel-bot/internal/platform/observability/logger"
	achievement2 "github.com/2000ostd/enssi-tel-bot/internal/usecase/commands/achievement"
	admin2 "github.com/2000ostd/enssi-tel-bot/internal/usecase/commands/admin"
	course2 "github.com/2000ostd/enssi-tel-bot/internal/usecase/commands/course"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/commands/quiz"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/commands/user"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/commands/word"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/jobs"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/queries/achievement"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/queries/admin"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/queries/course"
	"github.com/2000ostd/enssi-tel-bot/internal/usecase/queries/review"
	user2 "github.com/2000ostd/enssi-tel-bot/internal/usecase/queries/user"
	"github.com/google/wire"
	"gopkg.in/telebot.v4"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeBotApp now gets the logger as an input.
func InitializeBotApp(cfg *config.Config, db *gorm.DB, appLogger logger.Logger) (*BotApp, error) {
	userRepository := postgres.NewUserRepository(db)
	registerUserHandler := user.NewRegisterUserHandler(userRepository)
	achievementRepository := postgres.NewAchievementRepository(db)
	getProfileHandler := user2.NewGetProfileHandler(appLogger, userRepository, achievementRepository)
	quizRepository := postgres.NewQuizRepository(db, appLogger)
	wordRepository := postgres.NewWordRepository(db)
	handler := review.NewHandler(appLogger, userRepository, wordRepository)
	commandHandler := command.NewHandler(appLogger, registerUserHandler, getProfileHandler, userRepository, quizRepository, wordRepository, handler)
	courseRepository := postgres.NewCourseRepository(db)
	listCoursesHandler := course.NewListCoursesHandler(appLogger, courseRepository)
	getOverviewHandler := course.NewGetOverviewHandler(appLogger, courseRepository)
	getStatsHandler := admin.NewGetStatsHandler(appLogger, userRepository)
	getAllHandler := achievement.NewGetAllHandler(appLogger, achievementRepository)
	createCourseQuizHandler := quiz.NewCreateCourseQuizHandler(quizRepository, wordRepository)
	advanceWordHandler := course2.NewAdvanceWordHandler(appLogger, courseRepository, wordRepository, createCourseQuizHandler)
	startSessionHandler := course2.NewStartSessionHandler(appLogger, courseRepository, wordRepository, createCourseQuizHandler)
	createReviewQuizHandler := quiz.NewCreateReviewQuizHandler(quizRepository)
	cacheMediaHandler := word.NewCacheMediaHandler(wordRepository)
	string2 := _wireStringValue
	generator, err := imagegen.NewGenerator(string2)
	if err != nil {
		return nil, err
	}
	router := message.NewRouter(appLogger, listCoursesHandler, getOverviewHandler, getProfileHandler, getStatsHandler, getAllHandler, advanceWordHandler, startSessionHandler, userRepository, quizRepository, courseRepository, wordRepository, createReviewQuizHandler, cacheMediaHandler, achievementRepository, generator, handler)
	submitAnswerHandler := quiz.NewSubmitAnswerHandler(appLogger, quizRepository, wordRepository)
	awardProgressHandler := achievement2.NewAwardProgressHandler(achievementRepository)
	handleQuizCompletionHandler := course2.NewHandleQuizCompletionHandler(appLogger, courseRepository, wordRepository, createCourseQuizHandler, awardProgressHandler)
	handleWordMasteryHandler := achievement2.NewHandleWordMasteryHandler(appLogger, wordRepository, achievementRepository)
	callbackHandler := callback.NewHandler(appLogger, submitAnswerHandler, handleQuizCompletionHandler, quizRepository, achievementRepository, generator, userRepository, getOverviewHandler, handleWordMasteryHandler)
	botApp := &BotApp{
		CommandHandler:      commandHandler,
		MessageHandler:      router,
		CallbackHandler:     callbackHandler,
		RegisterUserHandler: registerUserHandler,
	}
	return botApp, nil
}

var (
	_wireStringValue = "assets/imgs/achievements_gen"
)

// InitializeWorkerApp now gets the logger as an input.
func InitializeWorkerApp(cfg *config.Config, db *gorm.DB, bot *telebot.Bot, appLogger logger.Logger) (*WorkerApp, error) {
	userRepository := postgres.NewUserRepository(db)
	wordRepository := postgres.NewWordRepository(db)
	quizRepository := postgres.NewQuizRepository(db, appLogger)
	createReviewQuizHandler := quiz.NewCreateReviewQuizHandler(quizRepository)
	notifier := telegram.NewNotifier(bot, userRepository)
	triggerDailyReviewsJob := jobs.NewTriggerDailyReviewsJob(appLogger, userRepository, wordRepository, quizRepository, createReviewQuizHandler, notifier)
	workerApp := &WorkerApp{
		TriggerDailyReviewsJob: triggerDailyReviewsJob,
	}
	return workerApp, nil
}

func InitializeBroadcastHandler(cfg *config.Config, db *gorm.DB, bot *telebot.Bot, appLogger logger.Logger) (admin2.BroadcastHandler, error) {
	userRepository := postgres.NewUserRepository(db)
	notifier := telegram.NewNotifier(bot, userRepository)
	broadcastHandler := admin2.NewBroadcastHandler(appLogger, userRepository, notifier)
	return broadcastHandler, nil
}

// wire.go:

// BotApp remains the same.
type BotApp struct {
	CommandHandler      *command.Handler
	MessageHandler      *message.Router
	CallbackHandler     *callback.Handler
	RegisterUserHandler user.RegisterUserHandler
}

// WorkerApp remains the same.
type WorkerApp struct {
	TriggerDailyReviewsJob *jobs.TriggerDailyReviewsJob
}

// --- Provider Sets ---
var userSet = wire.NewSet(postgres.NewUserRepository, wire.Bind(new(user3.Repository), new(*postgres.UserRepository)), user.NewRegisterUserHandler, user2.NewGetProfileHandler)

var courseSet = wire.NewSet(postgres.NewCourseRepository, wire.Bind(new(course3.Repository), new(*postgres.CourseRepository)), course.NewListCoursesHandler, course.NewGetOverviewHandler, course2.NewStartSessionHandler, course2.NewAdvanceWordHandler, course2.NewHandleQuizCompletionHandler)

var reviewSet = wire.NewSet(review.NewHandler)

var wordSet = wire.NewSet(postgres.NewWordRepository, wire.Bind(new(word2.Repository), new(*postgres.WordRepository)))

var statsHandlerSet = wire.NewSet(admin.NewGetStatsHandler)

var broadcastHandlerSet = wire.NewSet(admin2.NewBroadcastHandler)

var quizSet = wire.NewSet(postgres.NewQuizRepository, wire.Bind(new(quiz2.Repository), new(*postgres.QuizRepository)), quiz.NewCreateCourseQuizHandler, quiz.NewCreateReviewQuizHandler, quiz.NewSubmitAnswerHandler)

var achievementSet = wire.NewSet(postgres.NewAchievementRepository, wire.Bind(new(achievement3.Repository), new(*postgres.AchievementRepository)), achievement2.NewAwardProgressHandler, achievement.NewGetAllHandler, achievement2.NewHandleWordMasteryHandler)

var imagegenSet = wire.NewSet(wire.Value("assets/imgs/achievements_gen"), imagegen.NewGenerator, wire.Bind(new(achievement3.ImageGenerator), new(*imagegen.Generator)))

var notifierSet = wire.NewSet(telegram.NewNotifier, wire.Bind(new(notification.Notifier), new(*telegram.Notifier)))

var wordCacheSet = wire.NewSet(word.NewCacheMediaHandler)

var messageHandlerSet = wire.NewSet(message.NewAdminHandler, message.NewCourseHandler, message.NewProfileHandler, message.NewMainMenuHandler, message.NewRouter)
